config/routes.rb
PicPost::Application.routes.draw do

  root 'pages#home'

  scope :auth do
    scope :instagram do
      get 'connect',  to: 'sessions#connect'
      get 'callback', to: 'sessions#callback'
      get 'failure',  to: redirect('/')
      get 'sign-out', to: 'sessions#destroy', as: 'sign_out'
    end
  end

  resources :post_cards, only: [:new, :create, :show] do
    resources :charges, only: [:new, :create]
  end

end

app/models/concerns/lobable.rb
require 'active_support/concern'

module Lobable
  extend ActiveSupport::Concern

  included do
    after_initialize :initialize_lob

    def initialize_lob
      @lob = Lob()
    end
  end
end

app/models/post_card.rb
class PostCard < ActiveRecord::Base
  include Lobable

  mount_uploader :picture, PictureUploader

  before_save :build_address

  validates :name, :address_line1, :city, :state, :zip, :country, presence: true

  def paid?
    paid
  end

  private

  def build_address
    address = @lob.addresses.create(
      name: name,
      address_line1: address_line1,
      address_line2: address_line2,
      city: city,
      state: state,
      zip: zip,
      country: country
    )
    self.address_id = address['id']
  end

  def print!
    if paid?
      job = @lob.postcards.create(
        name,
        address_id,
        message: message,
        front: "https://dl.dropboxusercontent.com/u/15606280/postcard_postcard_post_card.pdf"
      )
      self.job_id = job['id']
      self.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= session[:access_token]
  end

  helper_method :current_user
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_filter :set_post_card, only: :create

  def new
  end

  def create
    customer = Stripe::Customer.create(card: params[:stripeToken])

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 500,
      description: 'Pic post customer',
      currency: 'AUD'
    )

    if charge.paid
      @post_card.paid = true
      @post_card.save
      @post_card.send(:print!)
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
  end

  private

  def set_post_card
    @post_card = PostCard.find(params[:post_card_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/post_cards_controller.rb
class PostCardsController < ApplicationController
  before_filter :get_image_urls, only: [:new]
  before_filter :set_post_card, only: [:show]

  def new
    @post_card = PostCard.new
  end

  def create
    @post_card = PostCard.new(post_card_params)
    respond_to do |format|
      if @post_card.save
        format.html { redirect_to new_post_card_charge_path(@post_card), notice: 'Success' }
        format.json { render action: 'show', status: :created, location: @post_card }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

  def get_image_urls
    if session[:image_urls].nil?
      response = Instagram.user_recent_media(access_token: session[:access_token])
      @image_urls = []

      response.each do |object|
        @image_urls << object.images.standard_resolution.url
      end
      session[:image_urls] = @image_urls
    else
      @image_urls = session[:image_urls]
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post_card
    @post_card = PostCard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_card_params
    params[:post_card].permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL)
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    session[:access_token] = response.access_token
    redirect_to new_post_card_path
  end

  def destroy
    session[:access_token] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_cards_helper.rb
module PostCardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag post_card_charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pic post</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <% if current_user %>
          <li><%= link_to "Sign out", sign_out_path %></li>
        <% else %>
          <li><%= link_to "Sign in", "/auth/instagram/connect", :'data-loading-text' => "Loading..." %></li>
        <% end %>
      </ul>
      <h3 class="text-muted"><%= link_to 'Pic post', root_path%></h3>
    </div>

    <%= yield %>

    <div class="footer">
      <hr>
      <p>© Pic post 2013</p>
    </div>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Pic post</h1>
  <p class="lead">Send your favourite instagram photos as postcards to your friends anywhere in the world.</p>

  <% if current_user %>
    <%= link_to "Make a new post card", "/post_cards/new", class: 'btn btn-success btn-lg' %>
  <% else %>
    <%= link_to "Sign in with Instagram", "/auth/instagram/connect", class: 'btn btn-success btn-lg', :'data-loading-text' => "Loading...", id: 'main-auth' %>
  <% end %>
</div>

app/views/post_cards/_form.html.erb
<%= form_for @post_card do |f| %>

  <div class="form-group">
    <%= f.text_field :address_line1, class: 'form-control', placeholder: 'Address line 1 (required)' %>
  </div>

  <div class="form-group">
    <%= f.text_field :address_line2, class: 'form-control', placeholder: 'Address line 2' %>
  </div>

  <div class="form-group">
    <%= f.text_field :city, class: 'form-control', placeholder: 'City (required)' %>
  </div>

  <div class="form-group">
    <%= f.text_field :zip, class: 'form-control', placeholder: 'Zip (required)' %>
  </div>

  <div class="form-group">
    <%= f.text_field :state, class: 'form-control', placeholder: 'State (required)' %>
  </div>

  <div class="form-group">
    <%= f.text_field :country, class: 'form-control', placeholder: 'Country (required)' %>
  </div>

  <hr>

  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Recipient name' %>
  </div>

  <div class="form-group">
    <%= f.text_area :message, class: 'form-control', placeholder: 'Message', rows: '12' %>
  </div>

  <hr>

  <div class="row">
    <% @image_urls.each do |url| %>
      <div class="col-sm-6 col-md-3 image-select" data-radio-button>
        <span class="thumbnail">
          <%= image_tag url %>
        </span>
        <%= f.radio_button :remote_picture_url, url %>
      </div>
    <% end %>
  </div>

  <hr>

  <div class="clearfix">
    <%= f.submit 'Submit', class: 'btn btn-success pull-right' %>
  </div>
<% end %>

app/views/post_cards/create.html.erb
<h1>PostCards#create</h1>
<p>Find me in app/views/post_cards/create.html.erb</p>

app/views/post_cards/new.html.erb
<%= render "form" %>

app/views/post_cards/show.html.erb
<h1>PostCards#show</h1>
<p>Find me in app/views/post_cards/show.html.erb</p>